# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: mail.arcor.de
    port: 25
    domain: arcor.de
    authentication: :login
    user_name: andrebruehl
    password: iwg7fh
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: mail.arcor.de
    port: 25
    domain: arcor.de
    authentication: :login
    user_name: andrebruehl
    password: iwg7fh
